# Generated by Django 2.1 on 2018-08-08 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='banner_url',
            new_name='bannerURL',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='header',
            new_name='headerTitle',
        ),
    ]
