# Generated by Django 2.1 on 2018-08-10 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180810_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computerip',
            name='ip',
            field=models.CharField(max_length=15),
        ),
    ]
