# Generated by Django 2.1 on 2018-08-10 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20180810_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='liked',
            field=models.TextField(default=''),
        ),
    ]
