# Generated by Django 2.1 on 2018-08-10 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20180810_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='liked',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
